# Generated by Django 6.1 on 2026-08-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16, verbose_name='Message role')),
                ('status', models.CharField(choices=[('pending', 'Pending (generation in progress)'), ('complete', 'Complete'), ('failed', 'Failed (retryable)')], default='pending', max_length=16, verbose_name='Generation status')),
                ('content', models.TextField(blank=True, default='', help_text='Blank is valid only while an assistant message is pending.')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.session')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='conversations_message_unique_session_sequence'), models.CheckConstraint(condition=models.Q(('role', 'user'), models.Q(('status', 'complete'), _negated=True), _negated=True), name='conversations_message_user_role_complete')],
            },
        ),
    ]
