# Generated by Django 6.1 on 2026-08-27 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'status', 'sequence'], name='conv_msg_session_status_seq'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-updated_at'], name='conv_session_user_updated'),
        ),
    ]
