# Generated by Django 6.1 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_chat_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='improvement_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='improvement_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='improvement_severity',
            field=models.CharField(
                blank=True,
                choices=[('none', 'No issues'), ('minor', 'Minor issues'), ('critical', 'Critical issues')],
                default='',
                max_length=16,
            ),
        ),
    ]
