"""End-to-end conversation integration tests (TASK-106).

Exercises the complete conversation lifecycle through the real API surface
only — register -> login -> JWT Bearer -> create session (topic + sample
generated by the LLM) -> stream chat turns -> failed generation -> retry ->
cross-user ownership — with OpenRouter mocked at the LLMProvider boundary
(SPEC Rule 4): the real TopicGenerationService, FallbackProvider and
StreamingCompletionService stack runs on top of a scripted fake provider.
"""

import json
from collections import deque
from collections.abc import Iterator

import pytest
from django.contrib.auth import get_user_model
from django.urls import reverse
from rest_framework.test import APIClient

import conversations.views as conversations_views
import llm.views as llm_views
from conversations.models import Message, Session
from conversations.topics import TopicGenerationService
from llm.exceptions import LLMAuthenticationError, LLMAvailabilityError
from llm.fallback import FallbackProvider
from llm.provider import LLMProvider
from llm.streaming import StreamingCompletionService
from llm.types import (
    CompletionRequest,
    CompletionResponse,
    StreamDelta,
    StreamEvent,
    StreamStart,
)

pytestmark = pytest.mark.django_db

REGISTER_URL = reverse("accounts:register")
LOGIN_URL = reverse("accounts:login")
PROFILE_URL = reverse("learning:profile")
SESSIONS_URL = reverse("conversations:sessions")

PASSWORD = "pw-123456"
MODEL = "openrouter/fake-primary"

TOPIC_PAYLOAD = {
    "title": "Ordering coffee abroad",
    "description": "Role-play buying coffee in a busy cafe and practise polite requests.",
}
SAMPLE_PAYLOAD = {
    "turns": [
        {"role": "assistant", "content": "Good morning! What can I get you today?"},
        {"role": "user", "content": "Hi! Could I have a latte, please?"},
        {"role": "assistant", "content": "Coming right up. Would you like anything else?"},
        {"role": "user", "content": "That is all, thank you!"},
    ]
}

USER_TEXT = "Could you help me order a coffee?"
COMPLETED_TEXT = "Of course! Let us practise."
STREAMED_TEXT = "PARTIAL-STREAMED-MARKER"
LEARNER = "frida"
STRANGER = "gustav"

SUCCESS_SCRIPT = (
    StreamStart(model=MODEL),
    StreamDelta(text="Of course!"),
    StreamDelta(text=" Let us practise."),
)


def completion(payload: dict) -> CompletionResponse:
    """Build a fake provider completion carrying one JSON payload."""
    return CompletionResponse(text=json.dumps(payload), model=MODEL)


def failing_stream(prefix: tuple[StreamEvent, ...], error: Exception) -> Iterator[StreamEvent]:
    """Emit the prefix events, then fail exactly like a collapsing stream."""
    yield from prefix
    raise error


class FakeOpenRouterProvider(LLMProvider):
    """Scripted OpenRouter stand-in recording every request it receives."""

    def __init__(self) -> None:
        self.completions: deque[CompletionResponse | Exception] = deque()
        self.complete_requests: list[CompletionRequest] = []
        self.stream_script: object = ()
        self.stream_requests: list[CompletionRequest] = []
        self.stream_emitted: list[StreamEvent] = []

    def queue_completion(self, outcome: CompletionResponse | Exception) -> None:
        self.completions.append(outcome)

    def complete(self, request: CompletionRequest) -> CompletionResponse:
        self.complete_requests.append(request)
        outcome = self.completions.popleft()
        if isinstance(outcome, Exception):
            raise outcome
        return outcome

    def stream(self, request: CompletionRequest) -> Iterator[StreamEvent]:
        self.stream_requests.append(request)
        if isinstance(self.stream_script, Exception):
            raise self.stream_script
        for event in self.stream_script:
            self.stream_emitted.append(event)
            yield event


@pytest.fixture
def api() -> APIClient:
    return APIClient()


def register_and_login(api_client: APIClient, *, username: str, email: str) -> dict:
    """Register a fresh user through the API and return their token payload."""
    registered = api_client.post(
        REGISTER_URL,
        {"username": username, "email": email, "password": PASSWORD},
        format="json",
    )
    assert registered.status_code == 201, registered.data
    logged_in = api_client.post(
        LOGIN_URL, {"username": username, "password": PASSWORD}, format="json"
    )
    assert logged_in.status_code == 200, logged_in.data
    return logged_in.data


@pytest.fixture
def learner(api) -> APIClient:
    """A registered learner speaking to the API with a real Bearer token."""
    tokens = register_and_login(api, username=LEARNER, email=f"{LEARNER}@example.com")
    api.credentials(HTTP_AUTHORIZATION=f"Bearer {tokens['access']}")
    return api


@pytest.fixture
def stranger() -> APIClient:
    """A second registered user with their own real Bearer token."""
    client = APIClient()
    tokens = register_and_login(client, username=STRANGER, email=f"{STRANGER}@example.com")
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {tokens['access']}")
    return client


@pytest.fixture
def openrouter(monkeypatch) -> FakeOpenRouterProvider:
    """Run the real service stack on top of a scripted fake OpenRouter.

    Session creation resolves topic and sample through the real
    TopicGenerationService and chat streaming through the real
    StreamingCompletionService; only the OpenRouter provider is fake.
    """
    fake = FakeOpenRouterProvider()
    fake.queue_completion(completion(TOPIC_PAYLOAD))
    fake.queue_completion(completion(SAMPLE_PAYLOAD))
    monkeypatch.setattr(
        conversations_views,
        "get_topic_service",
        lambda: TopicGenerationService(provider=FallbackProvider(provider=fake, models=(MODEL,))),
    )
    monkeypatch.setattr(
        llm_views,
        "get_streaming_service",
        lambda: StreamingCompletionService(
            provider=FallbackProvider(provider=fake, models=(MODEL,))
        ),
    )
    return fake


def create_session(api_client: APIClient, **payload) -> dict:
    """Create one session through the API and return its representation."""
    response = api_client.post(SESSIONS_URL, payload, format="json")
    assert response.status_code == 201, response.data
    return response.data


@pytest.fixture
def session(learner, openrouter) -> dict:
    """One session the learner created through the API (topic hint: travel)."""
    return create_session(learner, topic_hint="travel")


def user_id(username: str) -> int:
    return get_user_model().objects.get(username=username).id


def stream_url(session_pk) -> str:
    return reverse("conversations:session-message-stream", kwargs={"pk": session_pk})


def retry_url(session_pk, message_pk) -> str:
    return reverse(
        "conversations:session-message-retry",
        kwargs={"pk": session_pk, "message_pk": message_pk},
    )


def detail_url(session_pk) -> str:
    return reverse("conversations:session-detail", kwargs={"pk": session_pk})


def messages_url(session_pk) -> str:
    return reverse("conversations:session-messages", kwargs={"pk": session_pk})


def parse_frame(raw: bytes) -> tuple[str, dict]:
    lines = [line for line in raw.decode("utf-8").split("\n") if line != ""]
    assert len(lines) == 2, f"frame must be one event line + one data line: {raw!r}"
    event_line, data_line = lines
    assert event_line.startswith("event: "), raw
    assert data_line.startswith("data: "), raw
    return event_line.removeprefix("event: "), json.loads(data_line.removeprefix("data: "))


def read_frames(response) -> list[tuple[str, dict]]:
    return [parse_frame(chunk) for chunk in response.streaming_content]


def messages_payload(api_client: APIClient, session_pk) -> list[dict]:
    response = api_client.get(messages_url(session_pk), format="json")
    assert response.status_code == 200, response.data
    return response.data["results"]


# ---------------------------------------------------------------------------
# Session creation and topic generation.
# ---------------------------------------------------------------------------


class TestSessionCreationIntegration:
    def test_new_session_generates_topic_and_sample_and_persists_one_row(self, learner, openrouter):
        level_update = learner.patch(PROFILE_URL, {"level": "B2"}, format="json")
        assert level_update.status_code == 200, level_update.data

        response = learner.post(SESSIONS_URL, {"topic_hint": "travel"}, format="json")

        assert response.status_code == 201, response.data
        session = Session.objects.get()
        assert session.user_id == user_id(LEARNER)
        assert session.title == TOPIC_PAYLOAD["title"]
        assert session.topic == TOPIC_PAYLOAD["description"]
        assert session.topic_hint == "travel"
        assert session.learning_level == "B2"
        data = response.data
        assert data["id"] == session.id
        assert data["title"] == TOPIC_PAYLOAD["title"]
        assert data["topic"] == TOPIC_PAYLOAD["description"]
        assert data["topic_hint"] == "travel"
        assert data["learning_level"] == "B2"
        assert list(data["sample_conversation"]["turns"]) == SAMPLE_PAYLOAD["turns"]
        # The sample conversation is display data only — never chat history.
        assert Message.objects.count() == 0

        # The topic request carried the profile level and the learner's hint,
        # and the sample request was built from the generated topic.
        topic_request, sample_request = openrouter.complete_requests
        assert [m.role for m in topic_request.messages] == ["system", "user"]
        assert "travel" in topic_request.messages[-1].content
        assert "B2" in topic_request.messages[-1].content
        assert [m.role for m in sample_request.messages] == ["system", "user"]
        assert TOPIC_PAYLOAD["title"] in sample_request.messages[-1].content

    def test_created_session_appears_in_the_owner_listing(self, learner, openrouter):
        created = create_session(learner, topic_hint="travel")

        response = learner.get(SESSIONS_URL, format="json")

        assert response.status_code == 200
        assert response.data["count"] == 1
        assert [item["id"] for item in response.data["results"]] == [created["id"]]

    def test_empty_hint_lets_the_ai_choose_the_topic(self, learner, openrouter):
        response = learner.post(SESSIONS_URL, {}, format="json")

        assert response.status_code == 201, response.data
        assert response.data["topic_hint"] == ""
        assert response.data["learning_level"] == "AUTO"
        session = Session.objects.get()
        assert session.topic_hint == ""
        assert session.learning_level == "AUTO"
        user_prompt = openrouter.complete_requests[0].messages[-1].content
        assert "no preference" in user_prompt

    def test_topic_generation_failure_persists_no_session(self, learner, openrouter):
        openrouter.completions.clear()
        openrouter.queue_completion(
            LLMAvailabilityError("upstream unavailable", provider="openrouter")
        )

        response = learner.post(SESSIONS_URL, {"topic_hint": "travel"}, format="json")

        assert response.status_code == 503
        assert "detail" in response.data
        assert Session.objects.count() == 0

    def test_sample_generation_failure_persists_no_session(self, learner, openrouter):
        openrouter.completions.clear()
        openrouter.queue_completion(completion(TOPIC_PAYLOAD))
        openrouter.queue_completion(LLMAuthenticationError("bad key", provider="openrouter"))

        response = learner.post(SESSIONS_URL, {}, format="json")

        assert response.status_code == 502
        assert Session.objects.count() == 0


# ---------------------------------------------------------------------------
# Message creation and streaming lifecycle.
# ---------------------------------------------------------------------------


class TestStreamingChatLifecycle:
    def test_streamed_turn_is_delivered_and_persists_both_messages(
        self, learner, openrouter, session
    ):
        openrouter.stream_script = SUCCESS_SCRIPT

        response = learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")

        assert response.status_code == 200
        frames = read_frames(response)
        assert frames[0] == ("start", {"model": MODEL})
        assert [name for name, _ in frames[1:-1]] == ["delta", "delta"]
        assert frames[-1] == (
            "completed",
            {"text": COMPLETED_TEXT, "model": MODEL, "delta_count": 2},
        )

        rows = messages_payload(learner, session["id"])
        assert [(row["sequence"], row["role"], row["status"]) for row in rows] == [
            (1, "user", "complete"),
            (2, "assistant", "complete"),
        ]
        assert rows[0]["content"] == USER_TEXT
        assert rows[1]["content"] == COMPLETED_TEXT

    def test_llm_request_carries_topic_and_the_current_message(self, learner, openrouter, session):
        openrouter.stream_script = SUCCESS_SCRIPT

        read_frames(learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json"))

        (request,) = openrouter.stream_requests
        assert [m.role for m in request.messages] == ["system", "user"]
        assert TOPIC_PAYLOAD["title"] in request.messages[0].content
        assert TOPIC_PAYLOAD["description"] in request.messages[0].content
        assert request.messages[-1].content == USER_TEXT

    def test_chunks_arrive_incrementally(self, learner, openrouter, session):
        start = StreamStart(model=MODEL)
        delta_one = StreamDelta(text="Of course!")
        delta_two = StreamDelta(text=" Let us practise.")
        openrouter.stream_script = (start, delta_one, delta_two)

        response = learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")
        frames = response.streaming_content

        assert parse_frame(next(frames)) == ("start", {"model": MODEL})
        assert openrouter.stream_emitted == [start]
        assert parse_frame(next(frames)) == ("delta", {"text": "Of course!"})
        assert openrouter.stream_emitted == [start, delta_one]
        assert parse_frame(next(frames)) == ("delta", {"text": " Let us practise."})
        assert openrouter.stream_emitted == [start, delta_one, delta_two]
        assert parse_frame(next(frames))[0] == "completed"
        with pytest.raises(StopIteration):
            next(frames)

    def test_second_turn_extends_the_llm_context_with_history(self, learner, openrouter, session):
        openrouter.stream_script = SUCCESS_SCRIPT
        read_frames(learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json"))

        follow_up = "And how do I pay for it?"
        openrouter.stream_script = (StreamStart(model=MODEL), StreamDelta(text="By card!"))
        read_frames(learner.post(stream_url(session["id"]), {"text": follow_up}, format="json"))

        assert len(openrouter.stream_requests) == 2
        second = openrouter.stream_requests[1]
        assert [m.role for m in second.messages] == ["system", "user", "assistant", "user"]
        contents = [m.content for m in second.messages]
        assert USER_TEXT in contents
        assert COMPLETED_TEXT in contents
        assert contents[-1] == follow_up
        rows = messages_payload(learner, session["id"])
        assert [(row["sequence"], row["role"]) for row in rows] == [
            (1, "user"),
            (2, "assistant"),
            (3, "user"),
            (4, "assistant"),
        ]

    def test_failed_generation_persists_the_user_message_and_a_retryable_row(
        self, learner, openrouter, session
    ):
        openrouter.stream_script = LLMAvailabilityError("upstream collapsed", provider="openrouter")

        response = learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")

        frames = read_frames(response)
        assert [name for name, _ in frames] == ["error"]
        (error_name, error_data) = frames[-1]
        assert error_name == "error"
        assert "upstream collapsed" in error_data["error"]
        assert error_data["retryable"] is True
        assert set(error_data) == {"error", "retryable"}
        rows = messages_payload(learner, session["id"])
        assert [(row["sequence"], row["role"], row["status"]) for row in rows] == [
            (1, "user", "complete"),
            (2, "assistant", "failed"),
        ]
        assert rows[1]["content"] == ""

    def test_mid_stream_failure_never_persists_partial_output(self, learner, openrouter, session):
        error = LLMAvailabilityError("connection reset", provider="openrouter")
        openrouter.stream_script = failing_stream(
            (StreamStart(model=MODEL), StreamDelta(text=STREAMED_TEXT)), error
        )

        response = learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")
        frames = read_frames(response)

        assert [name for name, _ in frames[:2]] == ["start", "delta"]
        assert frames[-1][0] == "error"
        rows = messages_payload(learner, session["id"])
        assert rows[1]["status"] == "failed"
        assert STREAMED_TEXT not in rows[1]["content"]

    def test_blank_text_is_rejected_before_any_write_or_llm_call(
        self, learner, openrouter, session
    ):
        response = learner.post(stream_url(session["id"]), {"text": "   "}, format="json")

        assert response.status_code == 400
        assert "text" in response.data
        assert openrouter.stream_requests == []
        assert Message.objects.count() == 0


# ---------------------------------------------------------------------------
# Retry of failed generations.
# ---------------------------------------------------------------------------


class TestRetryIntegration:
    def test_retry_replaces_a_failed_generation_in_place(self, learner, openrouter, session):
        openrouter.stream_script = LLMAvailabilityError("upstream collapsed", provider="openrouter")
        failed = read_frames(
            learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")
        )
        assert failed[-1][0] == "error"
        assistant_id = messages_payload(learner, session["id"])[1]["id"]

        openrouter.stream_script = SUCCESS_SCRIPT
        response = learner.post(retry_url(session["id"], assistant_id))

        assert response.status_code == 200
        frames = read_frames(response)
        assert frames[0] == ("start", {"model": MODEL})
        assert frames[-1] == (
            "completed",
            {"text": COMPLETED_TEXT, "model": MODEL, "delta_count": 2},
        )

        rows = messages_payload(learner, session["id"])
        assert len(rows) == 2
        assert rows[0]["content"] == USER_TEXT
        assert rows[1]["id"] == assistant_id
        assert rows[1]["status"] == "complete"
        assert rows[1]["content"] == COMPLETED_TEXT

        # The retry rebuilt the turn from the same stored prompt.
        assert len(openrouter.stream_requests) == 2
        assert openrouter.stream_requests[1].messages[-1].content == USER_TEXT

    def test_repeated_failures_stay_retryable_until_the_stream_succeeds(
        self, learner, openrouter, session
    ):
        openrouter.stream_script = LLMAvailabilityError("still down", provider="openrouter")
        first_turn = read_frames(
            learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json")
        )
        assert first_turn[-1][0] == "error"
        assistant_id = messages_payload(learner, session["id"])[1]["id"]

        first_retry = learner.post(retry_url(session["id"], assistant_id))
        assert read_frames(first_retry)[-1][0] == "error"

        openrouter.stream_script = SUCCESS_SCRIPT
        second_retry = learner.post(retry_url(session["id"], assistant_id))
        assert read_frames(second_retry)[-1][0] == "completed"

        rows = messages_payload(learner, session["id"])
        assert len(rows) == 2
        assert rows[1]["status"] == "complete"

    def test_successful_assistant_messages_cannot_be_retried(self, learner, openrouter, session):
        openrouter.stream_script = SUCCESS_SCRIPT
        read_frames(learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json"))
        assistant_id = messages_payload(learner, session["id"])[1]["id"]
        stream_calls = len(openrouter.stream_requests)

        response = learner.post(retry_url(session["id"], assistant_id))

        assert response.status_code == 409
        assert len(openrouter.stream_requests) == stream_calls
        assert len(messages_payload(learner, session["id"])) == 2


# ---------------------------------------------------------------------------
# Ownership and authentication boundaries.
# ---------------------------------------------------------------------------


class TestOwnershipIntegration:
    def test_stranger_cannot_access_any_part_of_the_learners_conversation(
        self, learner, stranger, openrouter, session
    ):
        openrouter.stream_script = SUCCESS_SCRIPT
        read_frames(learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json"))
        rows = messages_payload(learner, session["id"])
        assistant_id = rows[1]["id"]

        detail = stranger.get(detail_url(session["id"]), format="json")
        messages = stranger.get(messages_url(session["id"]), format="json")
        streaming = stranger.post(
            stream_url(session["id"]), {"text": "hello from the outside"}, format="json"
        )
        retry = stranger.post(retry_url(session["id"], assistant_id))
        listing = stranger.get(SESSIONS_URL, format="json")

        assert detail.status_code == 404
        assert messages.status_code == 404
        assert streaming.status_code == 404
        assert retry.status_code == 404
        assert listing.status_code == 200
        assert listing.data["results"] == []
        # Nothing was written and no LLM call happened for the stranger.
        assert len(openrouter.stream_requests) == 1
        assert Message.objects.count() == 2
        assert messages_payload(learner, session["id"])[1]["content"] == COMPLETED_TEXT

    def test_missing_sessions_are_indistinguishable_from_foreign_ones(
        self, learner, stranger, openrouter
    ):
        create_session(learner, topic_hint="travel")

        missing_detail = stranger.get(detail_url(99999), format="json")
        missing_messages = stranger.get(messages_url(99999), format="json")
        missing_stream = stranger.post(stream_url(99999), {"text": "hi"}, format="json")

        assert missing_detail.status_code == 404
        assert missing_messages.status_code == 404
        assert missing_stream.status_code == 404
        assert openrouter.stream_requests == []
        assert Message.objects.count() == 0

    def test_anonymous_requests_are_rejected_across_the_conversation_api(
        self, learner, openrouter, session
    ):
        openrouter.stream_script = SUCCESS_SCRIPT
        read_frames(learner.post(stream_url(session["id"]), {"text": USER_TEXT}, format="json"))
        assistant_id = messages_payload(learner, session["id"])[1]["id"]
        anonymous = APIClient()

        assert anonymous.get(SESSIONS_URL, format="json").status_code == 401
        assert anonymous.post(SESSIONS_URL, {}, format="json").status_code == 401
        assert anonymous.get(detail_url(session["id"]), format="json").status_code == 401
        assert anonymous.get(messages_url(session["id"]), format="json").status_code == 401
        assert (
            anonymous.post(stream_url(session["id"]), {"text": "x"}, format="json").status_code
            == 401
        )
        assert anonymous.post(retry_url(session["id"], assistant_id)).status_code == 401
        assert Message.objects.count() == 2
