# Generated by Django 6.1 on 2026-08-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(help_text='The saved word or phrase exactly as selected.')),
                ('normalized_expression', models.TextField(help_text='Trimmed lowercase form of the expression for duplicate handling.')),
                ('definition', models.TextField(blank=True, default='')),
                ('translation', models.TextField(blank=True, default='')),
                ('pronunciation', models.CharField(blank=True, default='', max_length=255)),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=64)),
                ('example', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending (enrichment not yet done)'), ('complete', 'Complete'), ('failed', 'Failed (enrichment retryable)')], default='pending', max_length=16, verbose_name='Enrichment status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_items', to='conversations.message')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_items', to='conversations.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'normalized_expression'], name='vocabulary_user_normalized_idx')],
            },
        ),
    ]
